export const ORDER_BY_ID_REQUEST = "ORDER_BY_ID_REQUEST";
export const ORDER_BY_ID_SUCCESS = "ORDER_BY_ID_SUCCESS";
export const ORDER_BY_ID_FAIL = "ORDER_BY_ID_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";