
export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USERS_ORDER_REQUEST = "USERS_ORDER_REQUEST";
export const USERS_ORDER_SUCCESS = "USERS_ORDER_SUCCESS";
export const USERS_ORDER_FAIL = "USERS_ORDER_FAIL";
export const USERS_BY_ID_REQUEST = "USERS_BY_ID_REQUEST";
export const USERS_BY_ID_SUCCESS = "USERS_BY_ID_SUCCESS";
export const USERS_BY_ID_FAIL = "USERS_BY_ID_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS"